version: "3.9"

services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appointment_system

  redis:
    image: redis:7
    restart: always
    ports:
      - 6386:6379

volumes:
  postgres-data: